# Generated by Django 5.2.16 on 2026-07-09 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("vehicle_id", models.UUIDField(db_index=True)),
                ("driver_id", models.UUIDField(blank=True, default=None, null=True)),
                ("inspection_type", models.CharField(max_length=20)),
                ("odometer_value", models.PositiveIntegerField()),
                ("odometer_unit", models.CharField(max_length=10)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("inspected_at", models.DateTimeField()),
                (
                    "reviewed_by_id",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                ("review_notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection",
                "verbose_name_plural": "Inspections",
                "db_table": "inspection",
            },
        ),
        migrations.CreateModel(
            name="InspectionItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("category", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("result", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inspection.inspectionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inspection Item",
                "verbose_name_plural": "Inspection Items",
                "db_table": "inspection_item",
            },
        ),
        migrations.AddIndex(
            model_name="inspectionmodel",
            index=models.Index(
                fields=["vehicle_id", "status", "is_deleted"],
                name="insp_vehicle_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inspectionmodel",
            index=models.Index(fields=["inspected_at"], name="insp_inspected_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="inspectionitemmodel",
            constraint=models.UniqueConstraint(
                fields=("inspection", "item_id"), name="unique_inspection_item"
            ),
        ),
    ]
