# Generated by Django 5.2.16 on 2026-07-10 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique record identifier (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the last update to this record.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted. Never physically remove records.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC timestamp of soft deletion.', null=True)),
                ('sap_code', models.CharField(db_index=True, max_length=40)),
                ('code_group', models.CharField(db_index=True, max_length=40)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('catalog_type', models.CharField(default='B', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Template',
                'verbose_name_plural': 'Inspection Templates',
                'db_table': 'inspection_template',
                'indexes': [models.Index(fields=['is_active', 'is_deleted'], name='insp_tmpl_active_deleted_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sap_code', 'code_group', 'catalog_type'), name='unique_active_inspection_template_sap_key')],
            },
        ),
    ]
