# Generated by Codex on 2026-07-24

from django.db import migrations, models


def copy_old_template_text(apps, schema_editor):
    InspectionTemplate = apps.get_model("inspection", "InspectionTemplateModel")
    for template in InspectionTemplate.objects.all():
        template.code = template.sap_code
        template.group_text = template.category
        template.code_text = template.description
        template.defect_class = ""
        template.defect_class_text = ""
        template.save(
            update_fields=[
                "code",
                "group_text",
                "code_text",
                "defect_class",
                "defect_class_text",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0003_inspectionitemmodel_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectiontemplatemodel",
            name="code",
            field=models.CharField(blank=True, db_index=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="inspectiontemplatemodel",
            name="group_text",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="inspectiontemplatemodel",
            name="code_text",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="inspectiontemplatemodel",
            name="defect_class",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="inspectiontemplatemodel",
            name="defect_class_text",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(copy_old_template_text, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="inspectiontemplatemodel",
            name="unique_active_inspection_template_sap_key",
        ),
        migrations.RemoveField(
            model_name="inspectiontemplatemodel",
            name="sap_code",
        ),
        migrations.RemoveField(
            model_name="inspectiontemplatemodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="inspectiontemplatemodel",
            name="description",
        ),
        migrations.AlterField(
            model_name="inspectiontemplatemodel",
            name="code",
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="inspectiontemplatemodel",
            name="group_text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="inspectiontemplatemodel",
            name="code_text",
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name="inspectiontemplatemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code", "code_group", "catalog_type"),
                name="unique_active_inspection_template_sap_key",
            ),
        ),
    ]
