# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspection", "0004_align_inspection_template_with_sap_catalog"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inspectiontemplatemodel",
            name="unique_active_inspection_template_sap_key",
        ),
        migrations.RemoveField(
            model_name="inspectiontemplatemodel",
            name="catalog_type",
        ),
        migrations.RemoveField(
            model_name="inspectiontemplatemodel",
            name="defect_class",
        ),
        migrations.RemoveField(
            model_name="inspectiontemplatemodel",
            name="defect_class_text",
        ),
        migrations.AddConstraint(
            model_name="inspectiontemplatemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code", "code_group"),
                name="unique_active_inspection_template_sap_key",
            ),
        ),
    ]
