# Generated by Django 5.2.16 on 2026-07-19 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_manual_vehicle_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drivermodel',
            name='unique_active_customer_number',
        ),
        migrations.RemoveIndex(
            model_name='drivermodel',
            name='driver_status_deleted_idx',
        ),
        migrations.AddIndex(
            model_name='drivermodel',
            index=models.Index(fields=['status'], name='driver_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='drivermodel',
            constraint=models.UniqueConstraint(fields=('customer_number',), name='unique_driver_customer_number'),
        ),
    ]
