# Generated by FMMS.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0004_remove_drivermodel_unique_active_customer_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("DECOMMISSIONED", "DECOMMISSIONED"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
