# Generated by Django 5.2.16 on 2026-07-09 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("vehicle_id", models.UUIDField(db_index=True)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("description", models.CharField(max_length=500)),
                ("reported_at", models.DateTimeField()),
                ("severity", models.CharField(db_index=True, max_length=10)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("reported_by_id", models.UUIDField()),
                (
                    "inspection_id",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                (
                    "sap_defect_code",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "sap_notification_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "assigned_to_id",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fault",
                "verbose_name_plural": "Faults",
                "db_table": "fault",
                "indexes": [
                    models.Index(
                        fields=["vehicle_id", "status", "is_deleted"],
                        name="fault_vehicle_status_idx",
                    ),
                    models.Index(
                        fields=["severity", "status", "is_deleted"],
                        name="fault_severity_status_idx",
                    ),
                ],
            },
        ),
    ]
