# Generated by Django 5.2.16 on 2026-07-09 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SAPTransactionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("object_type", models.CharField(db_index=True, max_length=30)),
                ("object_id", models.UUIDField(db_index=True)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("max_retries", models.PositiveSmallIntegerField(default=3)),
                ("request_payload", models.JSONField(default=dict)),
                (
                    "response_payload",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "sap_document_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP Transaction",
                "verbose_name_plural": "SAP Transactions",
                "db_table": "sap_transaction",
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"], name="sap_tx_object_idx"
                    ),
                    models.Index(
                        fields=["status", "retry_count"], name="sap_tx_retry_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("idempotency_key",), name="unique_sap_idempotency_key"
                    )
                ],
            },
        ),
    ]
