# Generated by Django 5.2.16 on 2026-07-21 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPSyncRunModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique record identifier (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the last update to this record.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted. Never physically remove records.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC timestamp of soft deletion.', null=True)),
                ('trigger_source', models.CharField(choices=[('API', 'API'), ('CELERY', 'Celery'), ('JOB', 'Job')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial success')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('triggered_by_id', models.UUIDField(blank=True, default=None, null=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SAP Sync Run',
                'verbose_name_plural': 'SAP Sync Runs',
                'db_table': 'sap_sync_run',
            },
        ),
        migrations.CreateModel(
            name='SAPSyncRunItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique record identifier (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the last update to this record.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted. Never physically remove records.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC timestamp of soft deletion.', null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial success')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('summary', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integration.sapsyncrunmodel')),
            ],
            options={
                'verbose_name': 'SAP Sync Run Item',
                'verbose_name_plural': 'SAP Sync Run Items',
                'db_table': 'sap_sync_run_item',
            },
        ),
        migrations.AddIndex(
            model_name='sapsyncrunmodel',
            index=models.Index(fields=['trigger_source', 'started_at'], name='sap_sync_run_source_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sapsyncrunmodel',
            index=models.Index(fields=['status', 'started_at'], name='sap_sync_run_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sapsyncrunitemmodel',
            index=models.Index(fields=['name', 'finished_at'], name='sap_sync_item_name_time_idx'),
        ),
        migrations.AddIndex(
            model_name='sapsyncrunitemmodel',
            index=models.Index(fields=['sync_run', 'name'], name='sap_sync_item_run_name_idx'),
        ),
    ]
