# Generated by Django 5.2.16 on 2026-07-09 19:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("pr_id", models.UUIDField(db_index=True)),
                ("vendor_number", models.CharField(db_index=True, max_length=10)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("po_initiator_id", models.UUIDField()),
                (
                    "sap_po_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "approved_by_id",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "db_table": "purchase_order",
            },
        ),
        migrations.CreateModel(
            name="POLineItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("material_number", models.CharField(max_length=18)),
                (
                    "quantity_value",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("quantity_uom", models.CharField(max_length=10)),
                (
                    "unit_price_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("unit_price_currency", models.CharField(max_length=3)),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "po",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="procurement.purchaseordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "PO Line Item",
                "verbose_name_plural": "PO Line Items",
                "db_table": "po_line_item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("repair_order_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("requested_by_id", models.UUIDField()),
                (
                    "sap_pr_number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "approved_by_id",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Requisition",
                "verbose_name_plural": "Purchase Requisitions",
                "db_table": "purchase_requisition",
            },
        ),
        migrations.CreateModel(
            name="PRLineItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("material_number", models.CharField(max_length=18)),
                (
                    "quantity_value",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("quantity_uom", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=500)),
                (
                    "estimated_price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "estimated_price_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                (
                    "pr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="procurement.purchaserequisitionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "PR Line Item",
                "verbose_name_plural": "PR Line Items",
                "db_table": "pr_line_item",
            },
        ),
        migrations.AddIndex(
            model_name="purchaseordermodel",
            index=models.Index(fields=["pr_id", "is_deleted"], name="po_pr_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseordermodel",
            index=models.Index(fields=["status", "is_deleted"], name="po_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchaseordermodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("sap_po_number__gt", "")),
                fields=("sap_po_number",),
                name="unique_active_sap_po_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="polineitemmodel",
            constraint=models.UniqueConstraint(
                fields=("po", "item_id"), name="unique_po_line_item"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisitionmodel",
            index=models.Index(
                fields=["repair_order_id", "is_deleted"], name="pr_repair_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaserequisitionmodel",
            index=models.Index(fields=["status", "is_deleted"], name="pr_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="prlineitemmodel",
            constraint=models.UniqueConstraint(
                fields=("pr", "item_id"), name="unique_pr_line_item"
            ),
        ),
    ]
