# Generated by Django 5.2.16 on 2026-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisitionmodel",
            name="material_request_id",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
