# Generated by Django 5.2.16 on 2026-07-09 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PMPlanModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("vehicle_id", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("interval_value", models.PositiveIntegerField()),
                ("interval_unit", models.CharField(max_length=10)),
                ("trigger_type", models.CharField(max_length=20)),
                ("trigger_threshold", models.PositiveIntegerField()),
                ("initiator_id", models.UUIDField()),
                (
                    "last_triggered_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PM Plan",
                "verbose_name_plural": "PM Plans",
                "db_table": "pm_plan",
                "indexes": [
                    models.Index(
                        fields=["vehicle_id", "status", "is_deleted"],
                        name="pm_plan_vehicle_status_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PMWorkOrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC timestamp of soft deletion.",
                        null=True,
                    ),
                ),
                ("plan_id", models.UUIDField(db_index=True)),
                ("vehicle_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("scheduled_date", models.DateTimeField()),
                (
                    "triggered_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "sap_order_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PM Work Order",
                "verbose_name_plural": "PM Work Orders",
                "db_table": "pm_work_order",
                "indexes": [
                    models.Index(
                        fields=["plan_id", "status", "is_deleted"],
                        name="pm_wo_plan_status_idx",
                    ),
                    models.Index(
                        fields=["scheduled_date", "status"], name="pm_wo_scheduled_idx"
                    ),
                ],
            },
        ),
    ]
