# Generated by Django 5.2.16 on 2026-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="status",
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
