# Generated by Codex on 2026-07-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_vehicle_odometer_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclemodel",
            name="assistant_driver_customer_number",
            field=models.CharField(blank=True, db_index=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="vehiclemodel",
            name="primary_driver_customer_number",
            field=models.CharField(blank=True, db_index=True, default="", max_length=20),
        ),
    ]
