# Generated by Django 5.2.16 on 2026-07-19 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_align_vehicle_with_sap_odata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDriverAssignmentHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique record identifier (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the last update to this record.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted. Never physically remove records.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC timestamp of soft deletion.', null=True)),
                ('sync_run_id', models.UUIDField(db_index=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('synced_at', models.DateTimeField(db_index=True)),
                ('vehicle_id', models.UUIDField(db_index=True)),
                ('vehicle_number', models.CharField(db_index=True, max_length=18)),
                ('license_plate', models.CharField(blank=True, default='', max_length=20)),
                ('driver_role', models.CharField(choices=[('DRIVER', 'Driver'), ('ASSISTANT', 'Assistant')], db_index=True, max_length=20)),
                ('driver_customer_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Driver Assignment History',
                'verbose_name_plural': 'Vehicle Driver Assignment Histories',
                'db_table': 'vehicle_driver_assignment_history',
                'indexes': [models.Index(fields=['vehicle_number', 'synced_at'], name='veh_drv_hist_vehicle_time_idx'), models.Index(fields=['driver_customer_number', 'synced_at'], name='veh_drv_hist_driver_time_idx'), models.Index(fields=['sync_run_id', 'vehicle_number'], name='veh_drv_hist_run_vehicle_idx')],
            },
        ),
    ]
