# Generated by Django 5.2.16 on 2026-07-20 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicledriverassignmenthistorymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclemodel',
            name='unique_active_license_plate',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclemodel',
            name='unique_active_vehicle_number',
        ),
        migrations.RemoveIndex(
            model_name='vehiclemodel',
            name='vehicle_status_deleted_idx',
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['status'], name='vehicle_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('license_plate',), name='unique_vehicle_license_plate'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('vehicle_number',), name='unique_vehicle_number'),
        ),
    ]
