# Generated by FMMS.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0007_remove_vehiclemodel_unique_active_license_plate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("INACTIVE", "INACTIVE"),
                    ("UNDER_REPAIR", "UNDER_REPAIR"),
                    (
                        "WAITING_DRIVER_CONFIRMATION",
                        "WAITING_DRIVER_CONFIRMATION",
                    ),
                    ("SUSPENDED", "SUSPENDED"),
                    ("OUT_OF_SERVICE", "OUT_OF_SERVICE"),
                    ("DECOMMISSIONED", "DECOMMISSIONED"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
