# Generated by Django 5.2.16 on 2026-07-25 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_add_exited_center_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleComponentHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique record identifier (UUID4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of the last update to this record.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted. Never physically remove records.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='UTC timestamp of soft deletion.', null=True)),
                ('vehicle_id', models.UUIDField(db_index=True)),
                ('repair_order_id', models.UUIDField(db_index=True)),
                ('component_type', models.CharField(db_index=True, max_length=30)),
                ('material_number', models.CharField(db_index=True, max_length=40)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_of_measure', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('installed_at', models.DateTimeField(db_index=True)),
                ('recorded_by_id', models.UUIDField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Component History',
                'verbose_name_plural': 'Vehicle Component Histories',
                'db_table': 'vehicle_component_history',
                'indexes': [models.Index(fields=['vehicle_id', 'installed_at'], name='veh_comp_hist_vehicle_time_idx'), models.Index(fields=['vehicle_id', 'component_type'], name='veh_comp_hist_type_idx')],
            },
        ),
    ]
