# Generated by Django 5.2.16 on 2026-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_workshop_parts_closeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('UNDER_REPAIR', 'UNDER_REPAIR'), ('UNDER_EXTERNAL_REPAIR', 'UNDER_EXTERNAL_REPAIR'), ('WAITING_DRIVER_CONFIRMATION', 'WAITING_DRIVER_CONFIRMATION'), ('EXITED_CENTER', 'EXITED_CENTER'), ('SUSPENDED', 'SUSPENDED'), ('OUT_OF_SERVICE', 'OUT_OF_SERVICE'), ('DECOMMISSIONED', 'DECOMMISSIONED')], db_index=True, max_length=30),
        ),
    ]
