# Generated by Django 5.2.16 on 2026-07-11 17:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("repair", "0003_repair_order_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialRequestModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique record identifier (UUID4).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="UTC timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="UTC timestamp of the last update to this record.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this record has been soft-deleted. Never physically remove records.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="UTC timestamp of soft deletion.", null=True
                    ),
                ),
                ("repair_order_id", models.UUIDField(db_index=True)),
                ("status", models.CharField(db_index=True, max_length=30)),
                ("requested_by_id", models.UUIDField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft-deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "material_request"},
        ),
        migrations.CreateModel(
            name="InventoryTransactionModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("material_request_id", models.UUIDField(db_index=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("transaction_type", models.CharField(default="STOCK_ISSUE", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "inventory_transaction"},
        ),
        migrations.CreateModel(
            name="MaterialRequestItemModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.UUIDField()),
                ("material_number", models.CharField(max_length=18)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_of_measure", models.CharField(max_length=10)),
                (
                    "material_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="material.materialrequestmodel",
                    ),
                ),
            ],
            options={"db_table": "material_request_item"},
        ),
    ]
