# Generated by Django 5.2.16 on 2026-07-11 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransactionmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materialrequestitemmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='materialrequestmodel',
            index=models.Index(fields=['repair_order_id', 'is_deleted'], name='mr_repair_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequestmodel',
            index=models.Index(fields=['status', 'is_deleted'], name='mr_status_idx'),
        ),
    ]
