# Generated by Django 5.2.16 on 2026-07-09 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMMSUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique user identifier (UUID4).', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address — used as the login identifier.', max_length=254, unique=True)),
                ('full_name', models.CharField(help_text="User's full display name.", max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('TECHNICIAN', 'Technician'), ('VIEWER', 'Viewer (read-only)')], db_index=True, default='VIEWER', help_text='FMMS role — controls API permissions.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot log in.')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff users can access the Django admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of account creation (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last profile update (UTC).')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'FMMS User',
                'verbose_name_plural': 'FMMS Users',
                'db_table': 'fmms_users',
                'ordering': ['full_name'],
            },
        ),
    ]
