# Generated by Codex on 2026-07-16

from __future__ import annotations

from django.db import migrations, models


def populate_usernames(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    user_model = apps.get_model("authentication", "FMMSUser")
    used: set[str] = set()

    for user in user_model.objects.order_by("created_at", "id"):
        base = (user.email.split("@", 1)[0] if user.email else "user").strip()
        base = base[:140] or "user"
        username = base
        counter = 1
        while username.lower() in used or user_model.objects.filter(username=username).exclude(id=user.id).exists():
            suffix = f"-{counter}"
            username = f"{base[:150 - len(suffix)]}{suffix}"
            counter += 1
        user.username = username
        user.save(update_fields=["username"])
        used.add(username.lower())


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fmmsuser",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Username — used as the login identifier.",
                max_length=150,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="fmmsuser",
            name="email",
            field=models.EmailField(
                help_text="Email address for contact and notifications.",
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="fmmsuser",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Username — used as the login identifier.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
